### PR TITLE
Added the Voice section for Unified Communications

### PR DESCRIPTION
**Pull request by jorgedlcruz**
Added the Unified Communications section to the Admin Guide, as it’s
supported and bridged back to ZCS 8.7.x and above, original Adming
Guide for 8.6 is here:
https://www.zimbra.com/docs/ne/8.6.0/administration_guide/wwhelp/wwhimpl
/js/html/wwhelp.htm#href=860_admin_ne.Enabling_the_Voice_2fChat_Zimlets.
html

### CODE REVIEW

**Comment by grishick** [comment]
@jorgedlcruz I think you also need to change index.adoc to include this new section in the guide, otherwise it will not be accessible.

**Comment by gordyt** [comment]
@jorgedlcruz Greg is right, you need up update the `index.adoc` to include this new file.

**Comment by jorgedlcruz** [comment]
Done, it has now the index as well. I hope it's useful guys. It's still supported and works.

**Comment by fatkudu** [comment]
I'm inclined to think we should be targeting the *develop* branch for pull requests rather than *master*.

**Comment by gordyt** [comment]
@jorgedlcruz & @gaylebillat  - I rebased the `jorge-pages` pull request branch on top of `develop`, force-pushed it back to `origin`, and made a test export of the results.  There was a merge conflict that I had to fix during the rebase so please take a look at the export and make sure everything is OK.  The sample export is available [here](https://zimbra.github.io/adminguide/work-in-progress/index.html).

@jorgedlcruz If you want to make any additional changes to  this PR, please be sure that you reset your _local_ copy of the `jorge-pages` branch  to match what is in `origin` first.

If everything is OK, we can officially publish  the new doc export.

**Pull request merged**
