### PR TITLE
Minor content edits, title changed to add the release number as Gayle…

### PR DESCRIPTION
**Pull request by zextras-contrib**
… requested

### CODE REVIEW

**Comment by gordyt** [comment]
Added @gaylebillat and @jorgedlcruz as content reviewers.  Please see HTML export of this pull request [here](https://zimbra.github.io/adminguide/work-in-progress/index.html).

**Comment by gaylebillat** [comment]
Hi Gordon - thanks again for your help with this! Can the title be "8.8.x", please? So it covers future releases prior to 8.9. Thanks!

**Comment by gordyt** [comment]
@gaylebillat & @jorgedlcruz - The version number wasn't my call.  Apparently there are links in the ZExtras software to an 8.8.3 URL in our GitHub pages export of the admin guide (which won't exist until me or somebody else creates it).

My proposal is that we include this pull request--if the content is otherwise acceptable--in an 8.8.3 version export on GitHub pages.  All of the other information (this includes the initial version of the ZExtras stuff plus Gayle's editorial changes) are already available now in the 8.8.1 version export.

**Comment by gordyt** [comment]
@gaylebillat I should also mention that any documentation that is part of an earlier version will be automatically be part of newer version docs. We may want to talk more about how documentation links that are embedded in the software are handled.

**Comment by gaylebillat** [comment]
I approve this version! Sorry if you were waiting on me.

**Comment by gordyt** [comment]
merged & closed. updated html export

**Pull request closed without merging**
